#!/bin/bash
# Copyright 2016 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# fake_protoc is used in tests.
# It
# - dumps the args passed to it to stdout
#.- copies the last arg (if that's a file) beneath the --grpc_out dir

main() {
    echo $@  # first echo, the protoc tests need that.

    local proto_path=${!#}
    local out_dir=$(echo "$@" | sed 's/.*--grpc_out=\([^ ]*\).*/\1/')
    # fix out_dir in case protoc was run for the go plugin
    local out_dir=$(echo "$out_dir" | sed 's/.*--go_out=plugins=grpc:\([^ ]*\).*/\1/')
    echo "out_dir is $out_dir" 1>&2;
    local out_proto_path=${out_dir}/$proto_path
    local out_parent=$(dirname $out_proto_path)

    # no need to do a real copy; the test proto path may be fake, just touch it.
    mkdir -p -v $out_parent && echo "created parent of $out_proto_path" 1>&2;
    touch $out_proto_path
}

main "$@"
